name: Build Readit-project

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 26

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Project
        run: ./gradlew build